In [1]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/alexlei/Downloads/accepted_2007_to_2018Q4.csv', index_col=0, low_memory=False)

In [3]:
pd.options.display.max_rows = 200
df.dtypes

member_id                                     float64
loan_amnt                                     float64
funded_amnt                                   float64
funded_amnt_inv                               float64
term                                           object
int_rate                                      float64
installment                                   float64
grade                                          object
sub_grade                                      object
emp_title                                      object
emp_length                                     object
home_ownership                                 object
annual_inc                                    float64
verification_status                            object
issue_d                                        object
loan_status                                    object
pymnt_plan                                     object
url                                            object
desc                        

In [ ]:
# Convert the 'term' column to numeric

In [ ]:
df['term'] = df['term'].str.replace(' months', '')
df['term'] = pd.to_numeric(df['term'])

In [ ]:
df['term']

In [ ]:
# Convert the 'grade' column to numeric

In [ ]:
df['grade'].unique()

In [ ]:
mapping_term = {'A': 1, 'B': 0.833, 'C': 0.667, 'D': 0.5, 'E': 0.333, 'F': 0.167, 'G': 0}
#df.replace({'A': mapping, 'B': mapping, 'C': mapping, 'D': mapping, 'E': mapping, 'F': mapping, 'G': mapping})
#df['grade'] = pd.to_numeric(df['grade'])
df.applymap(lambda x: mapping_term.get(x) if x in mapping_term else x)

In [ ]:
# Convert the 'sub_grade' column to numeric

In [ ]:
df['sub_grade'].unique()

In [ ]:
mapping_subgrade = {
    'A5': 1.0, 'A4': 0.9706, 'A3': 0.9412, 'A2': 0.9118, 'A1': 0.8824,
    'B5': 0.8529, 'B4': 0.8235, 'B3': 0.7941, 'B2': 0.7647, 'B1': 0.7353,
    'C5': 0.7059, 'C4': 0.6765, 'C3': 0.6471, 'C2': 0.6176, 'C1': 0.5882,
    'D5': 0.5588, 'D4': 0.5294, 'D3': 0.5000, 'D2': 0.4706, 'D1': 0.4412,    
    'E5': 0.4118, 'E4': 0.3824, 'E3': 0.3529, 'E2': 0.3235, 'E1': 0.2941,
    'F5': 0.2647, 'F4': 0.2353, 'F3': 0.2059, 'F2': 0.1765, 'F1': 0.1471,
    'G5': 0.1176, 'G4': 0.0882, 'G3': 0.0588, 'G2': 0.0294, 'G1': 0,
}

# Use the map function to replace values based on the mapping dictionary
df['sub_grade'] = df['sub_grade'].map(mapping_subgrade)

In [ ]:
# Convert the 'emp_length' column to numeric

In [ ]:
df['emp_length'].unique()

In [ ]:
mapping_emp_length = {
    '10+ years': 1,
    '9 years': 0.9,
    '8 years': 0.8,
    '7 years': 0.7,
    '6 years': 0.6,
    '5 years': 0.5,
    '4 years': 0.4,
    '3 years': 0.3,
    '2 years': 0.2,
    '1 years': 0.1,
    '< 1 year': 0
}

df['emp_length'] = df['emp_length'].map(mapping_emp_length)

In [ ]:
df['emp_length'].unique()

In [ ]:
# Convert the 'home_ownership' column to numeric

In [6]:
df['home_ownership'].unique()

array([1. , 0.6, 0.8, 0.4, nan, 0. , 0.2])

In [5]:
mapping_home_ownership = {
    'MORTGAGE': 1,
    'OWN': 0.8,
    'RENT': 0.6,
    'ANY': 0.4,
    'OTHER': 0.2,
    'NONE': 0
}

df['home_ownership'] = df['home_ownership'].map(mapping_home_ownership)

In [ ]:
# Convert the 'verification_status' column to numeric

In [9]:
df['verification_status'].unique()

array([0. , 0.5, 1. , nan])

In [8]:
mapping_verification_status = {
    'Verified': 1,
    'Source Verified': 0.5,
    'Not Verified': 0
}

df['verification_status'] = df['verification_status'].map(mapping_verification_status)

In [ ]:
# Create a new column with start date of January 1, 2005
# the new column would contain the difference in days
# add the difference in days column to the current dataframe

In [10]:
df['issue_d'].unique()

array(['Dec-2015', 'Nov-2015', 'Oct-2015', 'Sep-2015', 'Aug-2015',
       'Jul-2015', 'Jun-2015', 'May-2015', 'Apr-2015', 'Mar-2015',
       'Feb-2015', 'Jan-2015', nan, 'Mar-2018', 'Feb-2018', 'Jan-2018',
       'Sep-2017', 'Aug-2017', 'Jul-2017', 'Jun-2016', 'May-2016',
       'Apr-2016', 'Sep-2018', 'Aug-2018', 'Jul-2018', 'Jun-2017',
       'May-2017', 'Apr-2017', 'Mar-2016', 'Feb-2016', 'Jan-2016',
       'Dec-2014', 'Nov-2014', 'Oct-2014', 'Sep-2014', 'Aug-2014',
       'Jul-2014', 'Jun-2014', 'May-2014', 'Apr-2014', 'Mar-2014',
       'Feb-2014', 'Jan-2014', 'Dec-2018', 'Nov-2018', 'Oct-2018',
       'Jun-2018', 'May-2018', 'Apr-2018', 'Dec-2011', 'Nov-2011',
       'Oct-2011', 'Sep-2011', 'Aug-2011', 'Jul-2011', 'Jun-2011',
       'May-2011', 'Apr-2011', 'Mar-2011', 'Feb-2011', 'Jan-2011',
       'Dec-2010', 'Nov-2010', 'Oct-2010', 'Sep-2010', 'Aug-2010',
       'Jul-2010', 'Jun-2010', 'May-2010', 'Apr-2010', 'Mar-2010',
       'Feb-2010', 'Jan-2010', 'Dec-2009', 'Nov-2009', 'O

In [17]:
df['issue_d_diff'] = df['issue_d'].copy()

id
68407277                                            Dec-2015
68355089                                            Dec-2015
68341763                                            Dec-2015
66310712                                            Dec-2015
68476807                                            Dec-2015
                                                      ...   
88985880                                            Oct-2016
88224441                                            Oct-2016
88215728                                            Oct-2016
Total amount funded in policy code 1: 1465324575         NaN
Total amount funded in policy code 2: 521953170          NaN
Name: issue_d_diff, Length: 2260701, dtype: object

In [19]:
df['issue_d_diff'] = df['issue_d_diff'].astype("string")

In [23]:
from datetime import datetime

# Define a reference date (January 1, 2005)
reference_date = datetime(2005, 1, 1)

# Create a list to store the differences in days
date_differences = []

# Iterate through the date strings
for date_string in df['issue_d_diff']:
    if isinstance(date_string, str):
        # Convert the date string to a datetime object
        date = datetime.strptime(date_string, '%b-%Y')

        # Calculate the difference in days from the reference date
        difference = (date - reference_date).days
        date_differences.append(difference)
    else:
        date_differences.append(None)  # Handle NaN values

# Create a DataFrame with the differences in days
df_2 = pd.DataFrame({'Date': df['issue_d_diff'], 'Difference (Days)': date_differences})

# Print the DataFrame
df_2

Date  Difference (Days)
id                                                                           
68407277                                          Dec-2015             3986.0
68355089                                          Dec-2015             3986.0
68341763                                          Dec-2015             3986.0
66310712                                          Dec-2015             3986.0
68476807                                          Dec-2015             3986.0
...                                                    ...                ...
88985880                                          Oct-2016             4291.0
88224441                                          Oct-2016             4291.0
88215728                                          Oct-2016             4291.0
Total amount funded in policy code 1: 1465324575      <NA>                NaN
Total amount funded in policy code 2: 521953170       <NA>                NaN

[2260701 rows x 2 columns]

In [24]:
df['issue_d_diff'] = df_2['Difference (Days)']

In [25]:
df['issue_d_diff']

id
68407277                                            3986.0
68355089                                            3986.0
68341763                                            3986.0
66310712                                            3986.0
68476807                                            3986.0
                                                     ...  
88985880                                            4291.0
88224441                                            4291.0
88215728                                            4291.0
Total amount funded in policy code 1: 1465324575       NaN
Total amount funded in policy code 2: 521953170        NaN
Name: issue_d_diff, Length: 2260701, dtype: float64

In [ ]:
# Convert the 'loan_status' column to numeric

In [28]:
df['loan_status'].unique()

array([1.  , 0.75, 0.  , 0.25, 0.5 ,  nan])

In [27]:
mapping_loan_status = {
    'Fully Paid': 1,
    'Does not meet the credit policy. Status:Fully Paid': 1,
    'Current': 0.75,
    'Late (16-30 days)': 0.5,
    'Late (31-120 days)': 0.25,
    'In Grace Period': 0.25,
    'Charged Off': 0,
    'Default': 0,
    'Does not meet the credit policy. Status:Charged Off': 0
}

df['loan_status'] = df['loan_status'].map(mapping_loan_status)

In [ ]:
scaler = MinMaxScaler(feature_range=(0, 1))

In [ ]:
df_filled = df.fillna(-1)
df_scaled = scaler.fit_transform(df_filled)

In [ ]:
scaled_df = pd.DataFrame(df_scaled, columns=df.columns)

In [ ]:
df.fillna('Null', inplace=True)

In [ ]:
# Preparing for X and y

In [ ]:
y = df['loan_status']

In [ ]:
X = df.drop(df.loc[:, 'hardship_flag':'settlement_term'].columns, axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
# Dropping NA in y will cause inconsistency in rows between y and X
# y = y.dropna()

In [ ]:
# Dropping NA in X will remove all rows
# X = X.dropna()

In [ ]:
# Create an Explainable Boosting Machine (EBM)
from interpret.glassbox import ExplainableBoostingClassifier
ebm = ExplainableBoostingClassifier()

# Fit the EBM on the training data
ebm.fit(X_train, y_train)